services:
  postgres:
    image: postgres:17
    container_name: flowops-postgres
    environment:
      POSTGRES_DB: flowops
      POSTGRES_USER: flowops
      POSTGRES_PASSWORD: flowops
      TZ: UTC
      PGTZ: UTC
    ports:
      - "5433:5432"
    volumes:
      - flowops-postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:8
    container_name: flowops-redis
    ports:
      - "6379:6379"
    volumes:
      - flowops-redis-data:/data
    restart: unless-stopped

  kafka:
    image: confluentinc/cp-kafka:7.7.1
    container_name: flowops-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
    volumes:
      - flowops-kafka-data:/var/lib/kafka/data
    restart: unless-stopped

volumes:
  flowops-postgres-data:
  flowops-redis-data:
  flowops-kafka-data: