spring.application.name=flowops
spring.datasource.url=jdbc:postgresql://localhost:5433/flowops?options=-c%20TimeZone=UTC
spring.datasource.username=flowops
spring.datasource.password=flowops

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
